//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Location_De_Voiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.CONTRATs = new HashSet<CONTRAT>();
        }
    
        public string ID_CLT { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string NUMBER_TELE { get; set; }
        public string N_CART_NATIONAL { get; set; }
        public string N_PERMIS { get; set; }
        public Nullable<System.DateTime> DATE_NISSANCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAT> CONTRATs { get; set; }
    }
}
