//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Location_De_Voiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRAT()
        {
            this.PAYEs = new HashSet<PAYE>();
        }
    
        public string ID { get; set; }
        public string ID_CLT { get; set; }
        public string MATRICULE { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
        public Nullable<decimal> MONTAN_TOTAL { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual VOITURE VOITURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYE> PAYEs { get; set; }
    }
}
