//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Location_De_Voiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYE
    {
        public string ID_PAYE { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> Prix_PAYE { get; set; }
        public string MODE_PAYE { get; set; }
    
        public virtual CONTRAT CONTRAT { get; set; }
    }
}
