//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Location_De_Voiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOITURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOITURE()
        {
            this.CONTRATs = new HashSet<CONTRAT>();
        }
    
        public string MATRICULE { get; set; }
        public string MODELE { get; set; }
        public string MARQUE { get; set; }
        public string CARBURANT { get; set; }
        public string DISPONIBLE { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAT> CONTRATs { get; set; }
    }
}
